steps:
  - id: "build and submit the dataflow job"
    name: maven:3.6.0-jdk-11-slim
    dir: 'demos/cloudbuild-dataflow-demo/streaming'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ./submit.sh StatesHavingPoorConnectivity \
          --project=geometric-edge-296513 \
          --stagingLocation=gs://geometric-edge-296513/stage/ \
          --gcpTempLocation=gs://geometric-edge-296513/temp/ \
          --runner=DataflowRunner \
          --autoscalingAlgorithm=THROUGHPUT_BASED \
          --maxNumWorkers=2 \
          --jobName=state \
          --subscription=dataflow_demo_subscription \
          --region=us-east1
    waitFor: ['-']
