steps:
  - id: "get build number"
    name: gcr.io/cloud-builders/git
    dir: 'cloudbuild-dataflow-demo/streaming'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git rev-parse --short HEAD > _BUILDNUMBER
    waitFor: ['-']
    
  - id: "sonar set up"
    name: maven:3.6.3-jdk-11
    dir: 'demos/cloudbuild-dataflow-demo/streaming'
    entrypoint: mvn
    args: ['clean install','sonar:sonar -Dsonar.login=4d60b1324656fff78944ed5f175189503018419e','org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar']
    waitFor: ['get build number']

  - id: "sonar analysis"
    name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
    args:
    - '-Dsonar.host.url=https://sonarcloud.io'
    - '-Dsonar.login=4d60b1324656fff78944ed5f175189503018419e'
    - '-Dsonar.projectKey=rakshitha-coder'
    - '-Dsonar.organization=rakshitha-coder'
    - '-Dsonar.sources=.'
    waitFor: ['sonar set up']
    
  - id: "build and submit the dataflow job"
    name: maven:3.6.3-jdk-11
    dir: 'demos/cloudbuild-dataflow-demo/streaming/'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          ./submit.sh StatesHavingPoorConnectivity \
          --project=geometric-edge-296513 \
          --stagingLocation=gs://geometric-edge-296513/stage/ \
          --gcpTempLocation=gs://geometric-edge-296513/temp/ \
          --runner=DataflowRunner \
          --autoscalingAlgorithm=THROUGHPUT_BASED \
          --maxNumWorkers=2 \
          --jobName=test \
          --buildNumber=${buildNumber} \
          --region=us-west1
    waitFor: ['sonar analysis']
    
    
