steps:
  - id: "get build number"
    name: gcr.io/cloud-builders/git
    dir: 'cloudbuild-dataflow-demo/streaming'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git rev-parse --short HEAD > _BUILDNUMBER
    waitFor: ['-']

  - name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
    args:
    - '-Dsonar.host.url=https://sonarcloud.io'
    - '-Dsonar.login={specify}'
    - '-Dsonar.projectKey={specify}'
    - '-Dsonar.organization={specify}'
    - '-Dsonar.sources=.'
tags: ['cloud-builders-community']
    
  - id: "build and submit the dataflow job"
    name: maven:3.6.3-jdk-11-slim
    dir: 'demos/cloudbuild-dataflow-demo/streaming/'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          ./submit.sh StatesHavingPoorConnectivity \
          --project=geometric-edge-296513 \
          --stagingLocation=gs://geometric-edge-296513/stage/ \
          --gcpTempLocation=gs://geometric-edge-296513/temp/ \
          --runner=DataflowRunner \
          --autoscalingAlgorithm=THROUGHPUT_BASED \
          --maxNumWorkers=2 \
          --jobName=test \
          --buildNumber=${buildNumber} \
          --region=us-west1
    waitFor: ['get build number']
    
    
